---
title: "R Notebook"
output: html_notebook
---

# Import

```{r}
library(tidyverse)
library(broom)
library(ggthemes)
library(lme4)
library(here)
library(viridis)
source('analysis_helpers.R')
```

```{r}
M_mat = read_csv('../data/deidentified/meta_tangrams_embeddings.csv', 
                na = c('[nan]'), col_types = cols(age = "c"), quote = '"') %>%
  mutate(feature_ind = row_number()) %>%
  left_join(read_csv('../data/deidentified/meta.csv', col_types = cols(age = "c"))) %>%
  select(-X1) 
```

```{r}
## Note that this will not knit and may need to be commented out for knitting
library(reticulate)
np <- import("numpy")
mat = np$load(here('data/deidentified/feats_tangrams_embeddings_rawavg.npy'))
saveRDS(mat, here('data/deidentified/feats_tangrams_embeddings_rawavg.RData'))
```

```{r}
F_mat = readRDS(here('data/deidentified/feats_tangrams_embeddings_rawavg.RData'))
dim(F_mat)
# combined.df <- compute_within_vs_across(M_mat, F_mat)
# 
# true_dprime = dprime(combined.df)
# 
# permuted_dprimes <- seq_len(1000) %>%
#   map_dbl(~ dprime(combined.df %>% mutate(source = sample(source))))
# 
# cat('CI for permuted=', sort(permuted_dprimes)[25], sort(permuted_dprimes)[975])
# cat('true=', true_dprime)
# combined.df %>%
#   ggplot(aes(x = empirical_stat, fill = source)) +
#     geom_density(adjust = 1.5, alpha = .5) +
#     xlab('pairwise cosine similarity') +
#     theme_few()
# ggsave('../../writing/figs/across_vs_within.pdf',  
#        height = 7, width = 10, units = 'cm', useDingbats = F)
```

### Utterances become increasingly consistent within interaction

Stats 

```{r, message=FALSE, cache=TRUE}
true_lmer.within <- M_mat %>%
  group_by(subid, target, age) %>%
  filter(length(text) == 4) %>%
  make_within_df(F_mat, 'cosine') %>% 
  filter(rep2 == rep1 + 1) %>% 
  mutate(sim = ifelse(is.nan(sim), NA, sim)) %>%
  ungroup()

# library(optimx)
true_lmer.within %>%
  lmer(sim ~ rep1 * age + (rep1 | subid),
       control = lmerControl(optimizer ='optimx',
                             optCtrl=list(method='nlminb')),
       data = .) %>%
  tidy()
```

Viz

```{r, message=FALSE, cache=TRUE}
true_lmer.within.toplot <- true_lmer.within %>%
  group_by(subid, rep1, age) %>%
  summarize(m = mean(sim,na.rm=T)) %>%
  group_by(rep1, age) %>%
  tidyboot::tidyboot_mean(m, na.rm=T)

true_lmer.within.toplot %>%
  ggplot(aes(x = rep1, y = empirical_stat, color = factor(age))) +
    geom_line() +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) + 
    scale_x_discrete(labels = c('(1,2)','(2,3)', '(3,4)', '(4,5)', '(5,6)' )) +
   # ylim(0.4, 1) +
    labs(x = 'rep', y = 'cosine similarity b/w first & final rep') +
    ggtitle('convergence within game') +
    theme_few() +
    guides(fill = F) 
    #theme(aspect.ratio = 1, legend.position = c(0.6, 0.5), text = element_text(size=18), 
          #element_line(size=1), element_rect(size=2, color="#00000"))
# ggsave('../../writing/figs/stability_mean.pdf', 
#        height = 10, width = 10, units = 'cm', useDingbats = F)
```

### Utterances become increasingly different across interactions

Stats 

```{r, message=FALSE, cache=TRUE}
true_lmer.across <- M_mat %>% 
   group_by(target, rep_num, age, director) %>%  
   do(flatten_sim_matrix(get_sim_matrix(., F_mat, method = 'cosine'), .$subid)) %>% 
  ungroup() %>%
  mutate(sim = ifelse(is.nan(sim), NA, sim)) %>%
  mutate(target = factor(target))

true_lmer.across %>%
  filter(age != 'adult') %>%
  mutate(age = as.numeric(age) - 6) %>%
  lmer(sim ~ rep_num * age + (1 + rep_num  | target),
       control = lmerControl(optimizer ='optimx',
                             optCtrl=list(method='nlminb')),
       data = .) %>%
  tidy()
```

Viz 

```{r}
true_lmer.across %>%
  group_by(dim1, age, director, rep_num) %>%
  summarize(m = mean(sim, na.rm=T)) %>%
  group_by(age, director, rep_num) %>%
  tidyboot::tidyboot_mean(m, na.rm=T) %>%
  ggplot(aes(x = rep_num, y = empirical_stat, color = as.factor(age))) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    geom_line()  +
    scale_x_continuous(breaks = c(1,2,3,4,5,6), labels = c(1,2,3,4,5,6)) +
    ylim(.4, 1) +
    ylab('cosine similarity') +
    ggtitle('divergence across pairs') +
    theme_few() +
    facet_wrap(~ director) +
    xlab('repetition') +
    guides(fill = F) 
    # theme(aspect.ratio = 1, legend.position = c(0.5, 0.8), text = element_text(size=18), 
    #       element_line(size=1), element_rect(size=2, color="#00000"))
ggsave('../../writing/figs/divergence_mean.pdf', height = 10, width = 10, units = 'cm', useDingbats = F)
```

# Other figures

## Fig. 6: tsne visualizations

```{r}
tsne <- read_csv('../data/deidentified/tsne_embeddings.csv') %>%
  mutate(rep_num = floor((trial -1) / 10)) %>%
  left_join(M_mat) %>%
  select(subid, target, rep_num, x_tsne, y_tsne) %>%
  mutate(r = useful::cart2pol(x_tsne, y_tsne)$r,
         theta = useful::cart2pol(x_tsne, y_tsne)$theta) %>%
  group_by(subid,  target) %>%
  arrange(rep_num) %>%
  mutate(finalTheta = last(theta)) %>%
  left_join(read_csv('../data/deidentified/meta.csv'))

tsne.toplot <- tsne %>% 
  filter(target == 'C1') %>% 
  filter(rep_num %in% c(0,3)) %>%
  filter(!is.na(x_tsne)) %>%
  group_by(subid) %>%
  mutate(next_x = lead(x_tsne) ,
         next_y = lead(y_tsne))
ggplot(tsne.toplot, aes(x = x_tsne, y = y_tsne)) +
    geom_point(data = subset(tsne.toplot, rep_num == 1),
               size = 1) +
    geom_segment(aes(xend = next_x, yend = next_y), 
                 arrow.fill = NULL, 
                 arrow = arrow(length = unit(0.30,"cm"), 
                               angle = 15, 
                               type = "closed")) +
    # uncomment this line to see text labels
    # geom_text(aes(label=contents), size = 1)+
    theme_few(20) +
    facet_wrap(~ age) +
    scale_shape_manual(values = c(21)) +
    scale_alpha_continuous(range = c(0.5, 1))+
    # scale_color_gradientn(colours = viridis(5))+
    #   theme(axis.title=element_blank(),
    #     axis.text=element_blank(),
    #     axis.ticks=element_blank()) +
    labs(x = "", y = "") +
    guides(shape = F, alpha = F) +
    theme(aspect.ratio = 1)  #+
# make it big to zoom in on text... 
# ggsave(filename = '../../writing/figs/tsne-tangramC_enlarged.pdf',
#        width = 15, height = 15)
# ggsave(filename = '../../writing/figs/tsne-tangramC.pdf',
#        width = 5, height = 5)
```

## supplemental figure 11 showing all tangrams

```{r}
tsne.all <- tsne %>%
  filter(rep_num %in% c(0,3)) %>%
  filter(!is.na(x_tsne)) %>%
  group_by(subid, target) %>%
  mutate(next_x = lead(x_tsne) ,
         next_y = lead(y_tsne))
ggplot(tsne.all, aes(x = x_tsne, y = y_tsne, color = finalTheta)) +
    geom_point(data = subset(tsne.all, rep_num == 1),
               size = 1) +
    facet_wrap(~ target, nrow = 4, ncol = 3) +
    geom_segment(aes(xend = next_x, yend = next_y), arrow.fill = NULL, 
                 arrow = arrow(length=unit(0.30,"cm"), angle=15, type = "closed"), ) +
    # uncomment to see text labels
    # geom_text(aes(label=contents), size = 1)+
    theme_few(20) +
    scale_shape_manual(values = c(21)) +
    scale_alpha_continuous(range = c(0.5, 1))+
    scale_color_gradientn(colours = viridis(5))+
      theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank()) +
    labs(x = "", y = "") +
    guides(color = F, shape = F, alpha = F) +
    theme(aspect.ratio = 1) 
ggsave(filename = './tsne-alltangrams.pdf',
       width = 15, height = 15)
```

