---
title: "Language use in tangrams"
author: "Robert Hawkins, Ashley Leung, and Dan Yurovsky"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: hide
---

## Imports 

```{r, message=FALSE, warning=FALSE, show = F}
library(tidyverse)
library(tidyboot)
library(janitor)
library(lme4)
library(lmerTest)
library(broom)

theme_set(theme_classic(base_size = 18))
```

## Aggregate csv files

```{r}
# get all files with participant data (this excludes meta.csv for now)
raw_csv_names <- dir(path = '../deidentified/', pattern = "*[0-9].csv", full.names = T)
meta <- read_csv('../deidentified/meta.csv')

raw_data <- raw_csv_names %>%
  map(read_csv) %>%             
  reduce(rbind) %>%                # read all csvs and combine into single data frame
  filter(type != 'practice') %>%   # remove practice trials
  group_by(subid, trial) %>%
  mutate(utt_number = row_number()) %>%
  group_by(subid, target) %>%
  mutate(rep_num = as.numeric(factor(trial))) %>%
  ungroup() %>%
  arrange(subid, trial) 

# Go through a lot of work just to get role mappings (ie. who is matcher, who is director?)
roles <- raw_data %>% filter(!is.na(selection)) %>% mutate(role = 'matcher') %>% 
  select(-type, -utterance, -correct, -selection, -target) %>% 
  rename(number_at_selection = utt_number) %>%
  complete(trial, nesting(subid, person)) %>%
  arrange(subid, trial) %>%
  mutate(role = ifelse(is.na(role), 'director', 'matcher')) %>%
  group_by(subid, trial) %>%
  mutate(number_at_selection = ifelse(is.na(first(number_at_selection)), 
                                      last(number_at_selection), 
                                      first(number_at_selection))) %>%
  mutate(rep_num = ifelse(is.na(first(rep_num)), last(rep_num), first(rep_num))) %>%
  ungroup()


data <- raw_data %>% 
  left_join(meta) %>%                          # combine with meta-data about age
  left_join(roles) %>%                         # combine with info about who had which role on each trial
  filter(utt_number < number_at_selection) %>% # remove utterances after selection was made
  group_by(subid, trial, person, role, target, rep_num, age) %>%
  summarize(utterance = paste0(utterance, collapse = ' ')) 
```

Write out combined data to import into python for nlp

```{r}
write_csv(data, '../deidentified/combined.csv')
```


## Origin of final descriptions

For each (contentful & lemmatized) word in the final utterance, we can look at which earlier rounds, if any, it appeared in.

```{r}
read_csv('../deidentified/word_matches.csv') %>%
  gather(round, match, `1_match`, `2_match`, `3_match`) %>%
  separate(round, into = c('round', 'garbage'), sep = '_') %>%
  group_by(subid, age, final_round_person, round) %>%
  summarize(match_rate = mean(match)) %>%
  ungroup() %>%
  mutate(match_target = ifelse(round == '2', 'same', 'diff'),
         final_round_person = ifelse(final_round_person == 'child', 'child-last', 'parent-last')) %>%
  group_by(final_round_person, age, round, match_target) %>%
  tidyboot_mean(match_rate) %>%
  ggplot(aes(x = round, y = empirical_stat)) +
    geom_bar(stat = 'identity') +
    facet_grid(final_round_person ~ age) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    theme_bw() +
    ylab('% final-round words occurring on round')

ggsave('appearance_on_earlier_rounds.pdf', width = 4, height = 3)
```

Look at *first* round final words appear

```{r}
read_csv('../deidentified/word_matches.csv') %>%  
  mutate(first_appearance = case_when(`1_match` ~ '1', 
                                      `2_match` ~ '2', 
                                      `3_match` ~ '3', 
                                      TRUE ~ 'never'),
         total = length(first_appearance),
         director = final_round_person,
         matcher = ifelse(final_round_person == 'parent', 'child', 'parent')) %>%
  filter(first_appearance != 'never') %>%
  mutate(introduced_by = ifelse(first_appearance == '2', director, matcher),
         introduced_by_parent = introduced_by == 'parent',
         introduced_by_self = introduced_by == director) %>%
  group_by(age, director) %>%
  tidyboot_mean(introduced_by_self) %>%
  ggplot(aes(x = as.character(age), y = empirical_stat, 
             group = director, color = director)) +
    geom_line() +
    geom_hline(yintercept = .5) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    theme_bw() +
    ylab('% final-round words introduced by self') +
    xlab("child age group") +
    theme(aspect.ratio = 1)

ggsave('introduction.pdf', width = 3.2, height = 3.2)
```

## Look at informativity

```{r}
read_csv('../deidentified/informativity.csv') %>%
  filter(tfidf != 0) %>%
  mutate(num_tangrams_occurred_with =  round(1 / ((2^tfidf) /10))) 
  gather(round, match, `1_match`, `2_match`, `3_match`) %>%
  separate(round, into = c('round', 'garbage'), sep = '_') %>%
  group_by(subid, age, final_round_person, round) %>%
  summarize(match_rate = mean(match)) %>%
  ungroup() %>%
  mutate(match_target = ifelse(round == '2', 'same', 'diff'),
         final_round_person = ifelse(final_round_person == 'child', 'child-last', 'parent-last')) %>%
  group_by(final_round_person, age, round, match_target) %>%
  tidyboot_mean(match_rate) %>%
  ggplot(aes(x = round, y = empirical_stat)) +
    geom_bar(stat = 'identity') +
    facet_grid(final_round_person ~ age) +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    theme_bw() +
    ylab('% final-round words occurring on round')

ggsave('appearance_on_earlier_rounds.pdf', width = 4, height = 3)
```

## Sanity checks

check for coding errors

```{r}
raw_data %>% 
  group_by(subid, trial) %>% tally() %>% filter(n == 1) %>% select(-n) %>% # get trial #s with 1 event
  left_join(raw_data) %>%
  group_by(person) %>% tally()
```