## Import

```{r}
library(tidyverse)
```

## Aggregate csv files (1a)

```{r}
# get all files with participant data (this excludes meta.csv for now)
raw_csv_names <- c(dir(path = '../deidentified/', pattern = "*[0-9].csv", full.names = T),
                   dir(path = '../deidentified/adult/', pattern = "*[0-9].csv", full.names = T))
meta <- read_csv('../deidentified/meta.csv')

raw_data <- raw_csv_names %>%
  map(read_csv) %>%             
  reduce(rbind) %>%                # read all csvs and combine into single data frame
  filter(type != 'practice') %>%   # remove practice trials
  group_by(subid, trial) %>%
  mutate(utt_number = row_number()) %>%
  group_by(subid, target) %>%
  mutate(rep_num = as.numeric(factor(trial)),
         correct = correct == 'Y') %>%
  ungroup() %>%
  arrange(subid, trial) 

# Go through a lot of work just to get role mappings (ie. who is matcher, who is director?)
roles <- raw_data %>% filter(!is.na(selection)) %>% mutate(role = 'matcher') %>% 
  select(-type, -utterance, -correct, -selection, -target) %>% 
  rename(number_at_selection = utt_number) %>%
  complete(trial, nesting(subid, person)) %>%
  arrange(subid, trial) %>%
  mutate(role = ifelse(is.na(role), 'director', 'matcher')) %>%
  group_by(subid, trial) %>%
  mutate(number_at_selection = ifelse(is.na(first(number_at_selection)), 
                                      last(number_at_selection), 
                                      first(number_at_selection))) %>%
  mutate(rep_num = ifelse(is.na(first(rep_num)), last(rep_num), first(rep_num))) %>%
  ungroup()

exchanges <- raw_data %>% 
  mutate(experiment = ifelse(subid >= 100, 'adult-adult', 'adult-child')) %>%
  left_join(meta) %>%                          # combine with meta-data about age
  left_join(roles, by = c('subid', 'trial', 'person', 'rep_num')) %>% 
  filter(!is.na(utterance)) %>%
  mutate(selection = ifelse(is.na(selection), 'none', selection))

combined_data <- exchanges %>% # combine with info about who had which role on each trial
  filter(utt_number < number_at_selection) %>% # remove utterances after selection was made
  group_by(subid, trial, person, role, target, rep_num, age) %>%
  summarize(utterance = paste0(utterance, collapse = ' '), correct = any(correct))
```

Write out combined data to import into python for nlp

```{r}
write_csv(exchanges, '../deidentified/exchanges.csv')
write_csv(combined_data, '../deidentified/combined.csv')
```


## Sanity checks

check for coding errors

```{r}
library(ggthemes)
accuracies <- raw_data %>% 
  left_join(meta) %>%                          # combine with meta-data about age
  left_join(roles, by = c('subid', 'trial', 'person', 'rep_num')) %>%
  filter(role == 'director') %>%
  filter(subid < 100) %>%
  group_by(subid, trial, person, correct,age) %>%
  tally() %>%
  group_by(subid, person,age) %>%
  summarize(m = mean(correct)) #%>%
  
badgames <- accuracies %>%
  filter(m <= 0.8) %>%
  pull(subid)

accuracies %>%
  spread(person, m) %>%
  ggplot(aes(x = child, y = parent, color = age)) +
    geom_jitter(width = 0.025, height = 0.025) +
    theme_few() +
    theme(aspect.ratio = 1) +
    ylim(0.4, 1.1) +
    xlim(0.4, 1.1) +
    xlab("accuracy when child is director") +
    ylab("accuracy when parent is director") +
    scale_color_gradient2()
ggsave('accuracy.pdf', height = 5, width = 5)
```

```{r}
not_correct_number_of_selections <- raw_data %>% 
  filter(selection != '') %>%
  group_by(subid, trial) %>% tally() %>% 
  ungroup() %>%
  complete(subid, trial, fill = list(n = 0)) %>%
  rowwise() %>%
  filter(n != 1) %>%
  unite(id, subid, trial) %>%
  pull(id)

raw_data %>% 
  group_by(subid, trial) %>% tally() %>% 
  filter(n == 1) %>% select(-n) %>% # get trial #s with 1 event
  unite(id, subid, trial) %>%
  rowwise() %>%
  filter(!(id %in% not_correct_number_of_selections)) %>%
  separate(id, into = c('subid', 'trial')) %>%
  knitr::kable('markdown')
```