---
title: "Tangram Transcripts"
author: "Ashley Leung, and Dan Yurovsky"
date: '`r Sys.Date()`'
output: 
  html_document:
    toc: false
    number_sections: false
    theme: lumen
    toc_float: false
    code_folding: hide
---
```{r, message=FALSE, warning=FALSE, show = F}
library(tidyverse)
library(here)
library(tidyboot)
library(knitr)
library(ggplot2)
library(janitor)
library(lme4)
library(lmerTest)
library(broom.mixed)

opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
               error = FALSE, cache = TRUE, tidy = FALSE)

theme_set(theme_classic(base_size = 18))
```

```{r read_data}

agedata <- read_csv(here("data/databaseid.csv")) %>%
  mutate(subid = as.character(subid))

demodata <- read_csv(here("data/tangramdemo.csv")) %>%
  select(-database_id) %>%
  remove_empty("cols")

gametrials <- read_csv(here("data/tangramgameresults.csv")) %>%
  mutate(type = if_else(nchar(leftpic) > 2, "practice", "test")) %>%
  mutate(trial = as.numeric(trial)+1)

## read transcripts and add col with database_id

transcripts <- list.files(here("data/coded"), "*.csv", full.names = T)

read_transcript <- function(file) {
  
  transcript <- read_csv(file) %>%
    remove_empty("cols") %>%
    mutate(database_id = parse_number(basename(file))) %>%
    #mutate(row = 1:n()) %>%
    filter(!is.na(Timeline.trial)) %>% 
    mutate(type = if_else(str_detect(Timeline.trial, "p"), "practice", 
                          "test"),
           trial = as.numeric(gsub("[^0-9]", "", Timeline.trial)))
}

data <- map(transcripts, read_transcript) %>%
  bind_rows() %>%
  left_join(agedata, by = "database_id")
```

```{r munge_data}

## for analysis

tidy_data <- data %>%
  left_join(gametrials, c("subid", "trial", "type")) %>%
  gather(person, utterance, Timeline.parentspeech, Timeline.childspeech) %>%
  mutate(utterance = if_else(utterance %in% c("<childspeech>", "<parentspeech>"),
                             as.character(NA), utterance)) %>%
  mutate(selection = if_else(Timeline.selection == "parent", "parent",
                            if_else(Timeline.selection == "child",
                                    "child", as.character(NA)))) %>%
  filter(!is.na(selection) | !is.na(utterance)) %>%
  filter(!is.na(trial)) %>%
  mutate(person = if_else(str_detect(person, "parent"), "parent", "child")) %>%
  filter(is.na(selection) | selection == person) %>%
  group_by(subid, type, trial) %>%
  arrange(Timeline.ordinal, .by_group = T) %>%
  mutate(pos = 1:n(),
         select_pos = which.max(!is.na(selection)),
         trial_selection = last(unique(selection)))
```

```{r data_checking}
tidy_data %>%
  ungroup() %>%
  distinct(age, subid) %>%
  group_by(age) %>%
  summarise(n = n()) %>%
  kable()
```

```{r conceptual_coding, eval = F, include = F}

## read transcripts without removing "na" (for coding conceptual pacts)

coding_transcript <- function(file) {
  
  transcript <- read_csv(file) %>%
    remove_empty("cols") %>%
    #mutate(row = 1:n()) %>% 
    mutate(database_id = parse_number(basename(file))) %>%
    mutate(type = if_else(str_detect(Timeline.trial, "p"), "practice", 
                          "test"),
           trial = as.numeric(gsub("[^0-9]", "", Timeline.trial)))
}

cdata <- map(transcripts, coding_transcript) %>%
  bind_rows() %>%
  left_join(agedata, by = "database_id")

## for conceptual pact coding
coding_data <- cdata %>%
  left_join(gametrials, c("subid", "trial", "type")) %>%
  gather(person, utterance, Timeline.parentspeech, Timeline.childspeech) %>%
  mutate(utterance = if_else(utterance %in% c("<childspeech>", "<parentspeech>"),
                             as.character(NA), utterance)) %>%
  mutate(selection = if_else(Timeline.selection == "parent", "parent",
                            if_else(Timeline.selection == "child",
                                    "child", as.character(NA)))) %>%
  filter(!is.na(selection) | !is.na(utterance)) %>%
  filter(!is.na(trial)) %>%
  mutate(person = if_else(str_detect(person, "parent"), "parent", "child")) %>%
  filter(is.na(selection) | selection == person) %>%
  group_by(subid, type, trial) %>%
  arrange(Timeline.ordinal, .by_group = T) %>%
  mutate(pos = 1:n(),
         select_pos = which.max(!is.na(selection)),
         trial_selection = last(unique(selection)))

```         

```{r coding-pacts, eval = F, include = F}
##output csv for conceptual pact coding

coding <- coding_data %>%
  arrange(subid, type, target, trial, Timeline.ordinal) %>%
  select(subid, type, trial, target, person, utterance, selection, correct) %>%
  filter(subid == 11 || subid == 46)
  

#newcols <- c("final_initial", "self", "other", "accept")
#coding[, newcols] <- NA

subids <- unique(coding$subid)
  
for (i in subids) {
   codingfile <- filter(coding, subid == i)
   name <- paste0(codingfile$subid[1], ".csv")
   write_csv(codingfile, here(paste0("deidentified/", name)), na="", append = FALSE)
 }
```


```{r grand_models}
model_data <- tidy_data %>%
  filter(type == "test", pos < select_pos) %>%
  mutate(length = str_count(utterance, " ") +1,
         correct = correct == "Y") %>%
  group_by(age, subid, correct, target, trial) %>%
  summarise(length = sum(length, na.rm = T),
            nturns = n()) %>%
  group_by(age, subid, target) %>%
  group_by(age, subid, target) %>%
  arrange(target, trial, .by_group = T) %>%
  mutate(target_trial = dense_rank(trial))


model_checks <- model_data %>%
  ungroup() %>%
  select(length, nturns) %>%
  gather(measure, original, length, nturns) %>%
  mutate(log = log(original)) %>%
  gather(type, value, original, log) %>%
  mutate(type = factor(type, levels = c("original", "log")))
  

ggplot(model_checks, aes(x = value)) + 
  geom_histogram() + 
  facet_grid(measure ~ type, scales = "free")

length_lm <- lmer(log(length) ~ age + target_trial + correct + trial +
                   (correct + target_trial | subid) + (1| target), 
                 control = lmerControl(optimizer = "bobyqa"),
                 data = model_data)

tidy(length_lm) %>%
  filter(effect == "fixed") %>%
  select(-group) %>%
  kable()


turns_lm <- lmer(log(nturns) ~ age + target_trial + correct + trial +
                   (correct + target_trial| subid) + (1| target), 
                 control = lmerControl(optimizer = "bobyqa"),
                 data = model_data)

tidy(turns_lm) %>%
  filter(effect == "fixed") %>%
  select(-group) %>%
  kable()
```
  
```{r indiv_models}

model_indiv_data <- tidy_data %>%
  filter(type == "test", pos < select_pos) %>%
  mutate(length = str_count(utterance, " ") +1,
         correct = T) %>%
  group_by(age, person, subid, correct, target, trial) %>%
  summarise(length = sum(length, na.rm = T),
            nturns = n()) %>%
  group_by(age, subid, target) %>%
  arrange(target, trial, .by_group = T) %>%
  mutate(target_trial = dense_rank(trial))


indiv_length_lm <- lmer(log(length) ~ age * person + person * target_trial +
                          age * target_trial + trial +
                 (person + target_trial |subid) + (1| target),
                 control = lmerControl(optimizer = "bobyqa"),
                 data = model_indiv_data)

tidy(indiv_length_lm) %>%
  filter(effect == "fixed") %>%
  select(-group) %>%
  kable()


indiv_turns_lm <-  lmer(log(nturns) ~ age * target_trial + person + 
                 (person + target_trial |subid) + (1| target),
                 control = lmerControl(optimizer = "bobyqa"),
                 data = model_indiv_data)

tidy(indiv_turns_lm) %>%
  filter(effect == "fixed") %>%
  select(-group) %>%
  kable()

```
  
```{r correctness}
model_data %>%
  group_by(age, target_trial, subid, target) %>%
  distinct(correct) %>%
  summarise(correct = mean(correct)) %>%
  summarise(correct = mean(correct))  %>%
  tidyboot_mean(correct) %>%
  ggplot(aes(x = target_trial, y = empirical_stat)) + 
  facet_wrap(~age) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) + 
  geom_line() +
  labs(x = "trial", y = "accuracy")

correct_lm <- glmer(correct ~ age * target_trial + trial +
                 (1|subid) + (1| target), family = "binomial",
                 control = glmerControl(optimizer = "bobyqa"),
                 data = model_data)


tidy(correct_lm) %>%
  filter(effect == "fixed") %>%
  select(-group) %>%
  kable()
```

```{r conceptual_pacts-plots}         
## reduction in length

# by age
jpeg("reduction.jpeg", width = 8, height = 6, units = "in", res = 600)
model_data %>%
  ungroup() %>%
  mutate(age = factor(age, labels = c("4 Years", "6 Years", "8 Years"))) %>%
  group_by(age, target_trial, subid) %>%
  summarise(length = mean(length)) %>%
  tidyboot_mean(length) %>%
  ggplot(aes(x = target_trial, y = empirical_stat)) + 
  facet_wrap(~ age) +
  #theme(panel.spacing.x = unit(1, "lines")) +
  theme(panel.border = element_rect(fill = NA, color = "black")) +
  geom_line() + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) +
  labs(x = "Round", y = "Length of referring expression (words)")
dev.off()

# overall
jpeg("overall_reduction.jpeg", width = 8, height = 6, units = "in", res = 600)
model_data %>%
  group_by(target_trial, subid) %>%
  summarise(length = mean(length)) %>%
  tidyboot_mean(length) %>%
  ggplot(aes(x = target_trial, y = empirical_stat)) + 
  geom_line() + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper))
dev.off()

## Plotting reduction in length

tidy_data %>%
  filter(type == "test", pos < select_pos) %>%
  mutate(length = str_count(utterance, " ") +1) %>%
  group_by(subid, correct, target, trial, person) %>%
  filter(person != trial_selection) %>%
  #filter(person == "parent") %>%
  summarise(length = sum(length, na.rm = T),
            nturns = n()) %>%
  group_by(subid, target) %>%
  mutate(trial = 1:n()) %>%
  filter(correct == "Y") %>%
  arrange(trial) %>%
  group_by(trial) %>%
  tidyboot_mean(length) %>%
  ggplot(aes(x = trial, y = empirical_stat)) + 
  geom_line() + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper))

## Plotting reduction in length (parent and child)

tidy_data %>%
  filter(type == "test", pos < select_pos) %>%
  mutate(length = str_count(utterance, " ") +1) %>%
  group_by(subid, correct, person, target, trial) %>%
  filter(person != trial_selection) %>%
  summarise(length = sum(length, na.rm = T),
            nturns = n()) %>%
  group_by(subid, target, person) %>%
  mutate(trial = 1:n()) %>%
  filter(correct == "Y") %>%
  arrange(trial) %>%
  group_by(person, trial) %>%
  tidyboot_mean(length) %>%
  ggplot(aes(x = trial, y = empirical_stat, color = person)) +
  geom_line() +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper))

## Parent and child

#model_indiv_data %>%
#  group_by(person, age, target_trial, subid) %>%
#  summarise(length = mean(length)) %>%
#  tidyboot_mean(length) %>%
#  ggplot(aes(x = target_trial, y = empirical_stat, color = person)) + 
#  facet_wrap(~ age) +
#  geom_line() + 
#  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper))
#dev.off()
  

jpeg("parent_child.jpeg", width = 10, height = 6, units = "in", res = 600)
tidy_data %>%
  filter(type == "test", pos < select_pos) %>%
  mutate(length = str_count(utterance, " ") +1) %>%
  ungroup %>%
  mutate(age = factor(age, labels = c("4 Years", "6 Years", "8 Years"))) %>%
  group_by(subid, age, correct, person, target, trial) %>%
  filter(person != trial_selection) %>%
  summarise(length = sum(length, na.rm = T),
            nturns = n()) %>%
  group_by(subid, age, target, person) %>%
  #filter(correct == "Y") %>%
  arrange(age, target, subid, person, trial) %>%
  mutate(trial = 1:n()) %>%
  filter(trial != 3) %>%
  group_by(age, person, trial) %>%
  tidyboot_mean(length) %>%
  ggplot(aes(x = trial, y = empirical_stat, color = person)) +
  facet_wrap(~ age) +
  theme(panel.border = element_rect(fill = NA, colour = "black")) +
  geom_line() +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) +
  xlim("1", "2") +
  labs(x = "Round", y = "Length of referring expression (words)")
dev.off()

```

```{r reaction time}
tidy_data %>%
  filter(rt == unique(rt)) %>%
  filter(rt < 50000) %>%
  ggplot(aes(rt)) +
  geom_histogram(binwidth = 1000)

tidy_data %>%
  filter(type == "test", person == trial_selection, rt < 120000) %>%
  group_by(subid, target, age, trial) %>%
  summarise(rt = mean(rt, na.rm = T),
            nturns = n()) %>%
  arrange(trial, .by_group = T) %>%
  mutate(trial = 1:n()) %>%
  group_by(trial, age) %>%
  tidyboot_mean(rt) %>%
  ggplot(aes(x = trial, y = empirical_stat))+
  facet_wrap(~age) +
  geom_line() +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper))

```

```{r accuracy}
gametrials %>% filter(type == "test") %>% 
  mutate(correct =  correct == "Y") %>%
  mutate(cum_correct = cummean(correct)) %>%
  ggplot(aes(x = trial, y = cum_correct)) + 
  geom_point()
```