---
title: "Tangram comprehension analysis"
author: "Ashley Leung, Robert Hawkins, and Dan Yurovsky"
date: '`r Sys.Date()`'
output: 
  html_document:
  toc: false
number_sections: false
theme: lumen
toc_float: false
code_folding: hide
---

```{r load-libraries}
library(here)
library(janitor)
library(readxl)
library(ggthemes)
library(tidyverse)
```

```{r load-data}
raw_turk_data <- read_csv(here("data/comprehension/dataFromMongo.csv")) %>%
  select(-age) %>%
  filter(!audioid %in% c("67_08", "67_08_b"))

check_correct <- raw_turk_data %>%
  filter(occurrence == "check") %>%
  mutate(check_correct = correct) %>%
  select(subid, check_correct)

passed_check <- check_correct %>%
  group_by(check_correct) %>%
  count() %>%
  pivot_wider(names_from = check_correct, values_from = n)
```

We kept `r passed_check$TRUE` out of `r passed_check$TRUE + passed_check$FALSE` participants.

```{r tidy-data}
database_ids <- read_csv(here("data/databaseid.csv")) %>%
  rename(gameid = subid) %>%
  select(gameid, age)

tidy_turk_data <- raw_turk_data %>%
  left_join(check_correct, by = c("subid")) %>%
  filter(check_correct, occurrence != "check") %>%
  separate(audioid, into = c("gameid", "gametrial"), sep = "_") %>%
  mutate(gameid = as.numeric(gameid),
         gametrial = as.numeric(gametrial)) %>%
  left_join(database_ids, by = ("gameid"))
```

## Results

Accuracy as a function of age, person, occurrence

```{r descriptive-plots}
d.boot.acc <- tidy_turk_data %>%
  group_by(age, person, occurrence) %>%
  tidyboot::tidyboot_mean(correct, nboot = 100) 

d.boot.acc %>%
  ggplot(aes(x = occurrence, y = empirical_stat, color = factor(age), linetype = person, group=interaction(person,age))) +
    geom_line() +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    theme_few()
```

```{r}
d.boot.rt <- tidy_turk_data %>%
  group_by(age, person, occurrence) %>%
  tidyboot::tidyboot_mean(reactiontime, nboot = 100) 

d.boot.rt %>%
  ggplot(aes(x = occurrence, y = empirical_stat, color = factor(age), linetype = person, group=interaction(person,age))) +
    geom_line() +
    geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0) +
    theme_few()
```